# Generated by Django 3.2 on 2021-11-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_alter_filme_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, to='filmes.Avaliacao'),
        ),
    ]
