# Generated by Django 3.2 on 2021-11-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_alter_filme_data_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.DurationField(),
        ),
    ]
